### ISSUE TITLE
xfinitywifi login? 

### ISSUE THREAD

**Issue by ghost** [schollz/raspberry-pi-turnkey#12]
Hi there 
VERY excited by this BUT I use xfinitywifi which is a service in the USA where AP's are on people's modems and we login whereever we see xfinitywifi. We then enter our email address and our xfinitywifi password. This connects our laptops to the wifi. I don't really see how to do this on your config. I thought the email was the one that got a message sent to it??

**Comment by schollz** [comment]
As in the readme

wpa_passphrase=ConnectToConnect

Also try connecting twice if it doesn't work

**Comment by ghost** [comment]
Hey Zack 
I got in on the second go so that works so I changed my question

**Comment by schollz** [comment]
I think its not possible to do it with Xfinity because the Pi will never think its "online" (because xfinity requires additional steps to go "online" once you get connected).

But shouldn't your modem also broadcast a personal/home WiFi SSID+password?

**Comment by ghost** [comment]
Hi Zack
I understand completely and xfinitywifi is a very obscure case and not worth even thinking about.  I don't have a wifi modem. I use xfinitywifi in a completely isolated environment so I connect with Pi0 and just connect to the web from that.  I was going to use your project to log the pi into the xfinitywifi and access it from there.

**Comment by schollz** [comment]
Yeah, so I'd be really excited if this can work on that but I don't know where to start. Let me know if you try!

**Comment by ghost** [comment]
Hi there
neither do I :-) as I said it's a real outlier and no worth thinking about as your idea is excellent the way it is. Sorry to have raised the issue

**Comment by schollz** [comment]
@sio2bagger No worries, its an issue worth thinking about so it definitely belongs here. 

I'm going to close it since I have no way of figuring it out (though I encourage anyone reading this to try).

**Comment by LordSAK** [comment]
any updates on this?
