### ISSUE TITLE
Spanish translation and Country Code on wpa_supplicant

### ISSUE THREAD

**Issue by yeyeto2788** [schollz/raspberry-pi-turnkey#17]
Hello @schollz,

Is there any way we can change the site language and the `wpa_supplicant` file to set country specific code on it?

Best regards.

**Comment by ilirb** [comment]
I don't see why not

- Fork the repo
- Change `wpa_conf` variables https://github.com/schollz/raspberry-pi-turnkey/blob/master/startup.py#L41 and https://github.com/schollz/raspberry-pi-turnkey/blob/master/startup.py#L49
- Change all the strings in `.py` and in `templates/`

To have a multilanguage selection then you can try to use `flask-babel` to extract string for translation files.

**Comment by yeyeto2788** [comment]
@ilirb thanks for your comment, I did fork the repo with this comment I can now try to adapt it to work with other languages. 

Regards.
