### ISSUE TITLE
No need to use sudo by root.

### ISSUE THREAD

**Issue by skx** [schollz/raspberry-pi-turnkey#2]
You mention adding this to the crontab of the root-user:

       @reboot cd /home/pi/raspberry-pi-turnkey && /usr/bin/sudo /usr/bin/python3 startup.py

Since this will be run by `root` there is no need for the use of sudo.  You could simplify to:

       @reboot cd /home/pi/raspberry-pi-turnkey &&  /usr/bin/python3 startup.py

**Comment by schollz** [comment]
I think I will actually need to change this.

Use the root crontab becomes problematic when you want to use some of the PATH variables of the `pi` user (i.e. in the case of using the Go/npm binaries I installed in the tutorial). In this case I think I will change it so `pi` is added to the sudoers and the crontab is run from the user.

**Comment by schollz** [comment]
I'm using `/etc/rc.local` now and switching to the `pi` user to fix this.
