### ISSUE TITLE
Connecting to Pi after

### ISSUE THREAD

**Issue by alejandroroiz** [schollz/raspberry-pi-turnkey#21]
Hello, I just installed your image and it works wonderfully, however, I wanted to continue using my rasp by connecting to it through ssh and keep adding stuff to the server.

My question is, after installing your image, is the pi "locked" (by locked I mean in its use, it is now binded to its use and it cannot be changed)? Or can I continue logging to it?

Wonderful project btw!

**Comment by schollz** [comment]
You should be able to log into it no problem. The turnkey just makes it so it connects to the right WiFi, after that it doesn't do anything.

**Comment by alejandroroiz** [comment]
I am having trouble ssh'ing to it. It asks me for a password I never setted, and when I use the one provided by your OS (it was the same URL also for snaptext [i guess you coded it that way :P]) it just displays a password error message.

Any ideas?

**Comment by schollz** [comment]
The default password should still be `raspberry`

**Comment by alejandroroiz** [comment]
Nope, tried and still failed :(, any other ideas?

**Comment by schollz** [comment]
Are you sshing as `pi@X` ?

**Comment by alejandroroiz** [comment]
Omg, I'm so dumb! Haha sorry, thanks!
