### ISSUE TITLE
 https://snaptext.live no longer works

### ISSUE THREAD

**Issue by Grandpa-G** [schollz/raspberry-pi-turnkey#27]
Don't know if you are working with this any more, but  https://snaptext.live doesn't exist.

**Comment by schollz** [comment]
Thanks, its been switched to https://snaptext.schollz.com, I will update the code

**Comment by Grandpa-G** [comment]
So this is your private website? That may not be the best option for long term. Could you include your web page source in the github so others could implement the idea locally?

Any suggestion how to get the new ip any other way?

**Comment by schollz** [comment]
Yeah its my website. But its open source and you could host it yourself: https://github.com/schollz/snaptext

There are other websites that do similar things, and you could adapt the scripts here to use any of them. Another example is https://patchbay.pub/

**Comment by Grandpa-G** [comment]
Thanks.

I am going to try to use the magic email address for phone carriers to send a text and see how that works.
