### ISSUE TITLE
How do I install Turnkey on Raspbian Stretch, please.

### ISSUE THREAD

**Issue by rarenu** [schollz/raspberry-pi-turnkey#3]
Dear Mr. schollz, I am using Google Assistant (GassistPi) installed on Raspbian Stretch. Please suggest me how to include Turnkey option for for my Google Assistant / Raspbian Stretch. ragoth@gmail.com

**Comment by schollz** [comment]
I've not tried it, but you should just be able to install GassistPi and then follow the instruction on this tutorial to add the Turnkey implementation.

**Comment by rarenu** [comment]
Hi, thank you so much for your immediate reply. I am 71 retired telecom
engineer and my hobby is Raspberry pi. I have been looking for an option
like this in Raspberry pi for a long time. It is really a nice project and
thank you again for publishing it.
I will try it and get back to you.
With great regards,
Ragothaman R.

**Comment by RAHUL1407** [comment]
Dear Mr.schollz , I m very thankful to u for this project , plz tell me  how to reset pi for new ssid and pswd?

**Comment by schollz** [comment]
@RAHUL1407, currently the only way to reset the pi once it has been connected is to turn off the WiFi that it is connected to and then turn off and on the pi.

@rarenu Thanks for the kind words, don't hesitate to let me know if you need any assistance

**Comment by rarenu** [comment]
Dear Mr. Zack,
I tried to install your "turnkey" on my GassistPi installation after
switching "OFF" my Wifi and enabling SSH, connecting LAN cable and using
puTTY in my Laptop.  The installation was smooth, but 192.168.4.1's web
page is not loading on my browsers. On my RPI GUI screen, I see this under
network icon:
 "wlan0: Associated with ConnectToConnect
  wlan0:Configured 192.168.4.1/24
  eth0:Link is down"

under this condition, even if I set my Wifi credentials in RPI, the
internet is not getting connected.

Also please clarify, during installation it shows a set of options to
choose in DHCP configuration set,up whether to update or to keep the
existing setup etc., in that the default is keeping the existing setup
(option "N") and I selected "N". Is correct or do I have choose some other
option, please advice.

Please help me.

With Great regards,
Ragothaman Ramanujam

**Comment by schollz** [comment]
You don't see the web page? Did you connect to "ConnectToConnect" AP?

**Comment by rarenu** [comment]
Hi, Thanks for your reply.
Yes, It is connected to "ConnectToConnect" but no webpage loading." Please
suggest any trouble shooting tips, please.

Please also clarify, during installation it shows a set of options to
choose in DHCP configuration setup, whether to update or to keep the
existing setup etc., in that the default is keeping the existing setup
(option "N") and I selected "N". Is correct or do I have choose some other
option, please advice.

On 03-Mar-2018 5:10 AM, "Zack" <notifications@github.com> wrote:

You don't see the web page? Did you connect to "ConnectToConnect" AP?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/schollz/raspberry-pi-turnkey/issues/3#issuecomment-370089117>,
or mute the thread

**Comment by schollz** [comment]
Selecting the default is correct when doing the DHCP configuration.

Can you try connecting to "ConnectToConnect" again? Sometimes it takes 30 seconds to a minute to load the page. Also make sure to refresh your browser and also try disconnecting and reconnecting if it doesn't work.

**Comment by rarenu** [comment]
Thank you for your guidance. I will try that.
Thanks again.
