### ISSUE TITLE
not getting page

### ISSUE THREAD

**Issue by RAHUL1407** [schollz/raspberry-pi-turnkey#6]
when i connected to ConnectToConnect , after that not getting  page with 192.168.4.1.

**Comment by RAHUL1407** [comment]
i got the page .

**Comment by RAHUL1407** [comment]
but after that  when i connecting to desktop it was  crushed

**Comment by schollz** [comment]
@RAHUL1407, what do you mean crushed?

**Comment by RAHUL1407** [comment]
When I flash Ur img on my sd card ...I got .access ssid and I putted pswd also after words I got page ..I putted my email, WiFi ssid to which I want to configure and pswd but I did not get any IP ....after wards I connected my rasberry pi zero w to desktop ..but  after reboot it was stopped with ..uneven screen

**Comment by RAHUL1407** [comment]
Plz help if u can give fresh IMG file.

**Comment by schollz** [comment]
@RAHUL1407 I'm not sure what is going on. It sounds like it worked? I'm not sure what an uneven screen is. Which image did you use? There is a new one I uploaded yesterday: https://raspberry-pi-turnkey.schollz.com/2018-02-19-turnkey.img.zip. You could try that.

**Comment by RAHUL1407** [comment]
I tried with that only. . raspberry pi after flashing  IMG...file and configuration I m not getting any IP addresses for RPI and when I connected to desktop ....RPI booting but after sometime.....some dots...and unable to access addresses msg is coming...proper IMG is not cmg

**Comment by schollz** [comment]
@RAHUL1407 It sounds like its working, but it is slow (Raspberry Pi's are not fast computers). You say you are not getting an IP address - but once it is connected you can double-check by logging into your router and looking for its IP address.

**Comment by RAHUL1407** [comment]
I m not getting RPI terminal also ..after connecting to desktop..
